// src/app/lib/payroll/templates/types.ts
export type PayrollTemplateType = 'ISURF_STANDARD' | 'BLUERIDGE';

export interface TemplateConfig {
  id: PayrollTemplateType;
  name: string;
  description: string;
  requiredColumns: string[];
  canonicalHeaders: Record<string, string>;
}

export const PAYROLL_TEMPLATES: Record<PayrollTemplateType, TemplateConfig> = {
  ISURF_STANDARD: {
    id: 'ISURF_STANDARD',
    name: 'Isurf Standard Template',
    description: 'Original Isurf payroll template',
    requiredColumns: [
      'Name', 'EMAIL', 'Gross Pay', 'Basic', 'Housing', 'Transport', 
      'Dressing', 'Leave Allowance', 'Entertainment', 'Utility', 'Payee', 
      'Pension', 'Deduction', 'Bonus KPI', 'Net Salary', 'FINAL GROSS', 
      'Medical Contribution', 'No of Working Days in the Month', 'No of days Worked'
    ],
    canonicalHeaders: {
      's/n': 'S/N',
      'name': 'Name',
      'resumption date': 'Resumption Date',
      'no of working days in the month': 'No of Working Days in the Month',
      'no of days worked': 'No of days Worked',
      'gross pay': 'Gross Pay',
      'prorated gross pay': 'Prorated Gross Pay',
      'basic': 'Basic',
      'housing': 'Housing',
      'transport': 'Transport',
      'dressing': 'Dressing',
      'leave allowance': 'Leave Allowance',
      'entertainment': 'Entertainment',
      'utility': 'Utility',
      'salary of attendance': 'Salary Of Attendance',
      "prorated gross pay with extra all'wce": "PRORATED GROSS PAY WITH EXTRA ALL'WCE",
      'taxable income': 'TAXABLE INCOME',
      'consolidated relief': 'Consolidated Relief',
      'payee': 'Payee',
      'pension': 'Pension',
      'deduction': 'Deduction',
      'bonus kpi': 'Bonus KPI',
      'net salary': 'Net Salary',
      'final gross': 'FINAL GROSS',
      'medical contribution': 'Medical Contribution',
      'employer pension': 'Employer Pension',
      'nsitf': 'NSITF',
      'prorated sub total invoice': 'Prorated Sub Total Invoice',
      'mgt fee': 'Mgt Fee',
      'vat on management fee @7.5%': 'Vat on Management Fee @7.5%',
      'total invoice value': 'Total Invoice Value',
      'email': 'EMAIL',
      'month': 'Month',
      'month': 'MONTH',
      'year': 'Year',
      'year': 'YEAR',
    }
  },
  BLUERIDGE: {
    id: 'BLUERIDGE',
    name: 'Blueridge Template',
    description: 'Blueridge payroll template with different structure',
    requiredColumns: [
      'Staff ID', 'Name', 'Basic Salary before Verify(coe)', 
      'Housing', 'Transport', 'Other Allowance',
      'Final Gross Income This Month (Salary, OI, CA, TA, OI & PB)',
      'Tax Payable This Month (Salary, OI, CA, TA, OI & PB)',
      'Employee Pension Deduction',
      'Total Net (Salary, OI, CA, TA, OI & PB)',
      'Working Days', 'Worked Days'
    ],
    canonicalHeaders: {
      's/n': 'S/N',
      'month': 'Month',
      'staff id': 'Staff ID',
      'name': 'Name',
      'country': 'Country',
      'state': 'State',
      'city': 'City',
      'region': 'Region',
      'business line': 'Business Line',
      'position verify (coe)': 'Position verify (coe)',
      'resumption date': 'Resumption Date',
      'exit date': 'Exit Date',
      'working days': 'Working Days',
      'worked days': 'Worked Days',
      'basic salary before verify(coe)': 'Basic Salary before Verify(coe)',
      'basic salary adjustment difference': 'basic Salary adjustment difference',
      'target performance bonus before verify(coe)': 'Target Performance Bonus before Verify(coe)',
      'hmo': 'HMO',
      'this month\'s gross': 'This Month\'s Gross',
      'overtime income (oi)': 'Overtime Income (OI)',
      'communication allowance (ca)': 'Communication Allowance (CA)',
      'transportation allowance (ta)': 'Transportation Allowance (TA)',
      'outstanding income (oi)': 'Outstanding Income (OI)',
      'performance bonus (pb)': 'Performance Bonus (PB)',
      'basic': 'Basic',
      'housing': 'Housing',
      'transport': 'Transport',
      'other allowance': 'Other Allowance',
      'final gross this month (salary + oi + ca + ta + oi)': 'Final Gross This Month (Salary + OI + CA + TA + OI)',
      'final gross performance bonus this month': 'Final Gross Performance Bonus This Month',
      'final gross income this month (salary, oi, ca, ta, oi & pb)': 'Final Gross Income This Month (Salary, OI, CA, TA, OI & PB)',
      'gross monthly (salary, oi, ca, ta, oi) for crs purpose': 'Gross Monthly (Salary, OI, CA, TA, OI) for CRS Purpose',
      'gross performance bonus for crs purpose': 'Gross Performance Bonus for CRS Purpose',
      'consolidated relief allowance (salary, oi, ca, ta, oi)': 'Consolidated Relief Allowance (Salary, OI, CA, TA, OI)',
      'consolidated relief allowance (salary, oi, ca, ta, oi + perfomance bonus)': 'Consolidated Relief Allowance (Salary, OI, CA, TA, OI + Perfomance Bonus)',
      'employee pension deduction': 'Employee Pension Deduction',
      'total non-taxable income & tax exempt item': 'Total Non-Taxable Income & Tax Exempt Item',
      'total reliefs and deductions (salary, oi, ca, ta, oi)': 'Total Reliefs and Deductions (Salary, OI, CA, TA, OI)',
      'total reliefs and deductions (salary, oi, ca, ta, oi & pb)': 'Total Reliefs and Deductions (Salary, OI, CA, TA, OI & PB)',
      'taxable income - (salary, oi, ca, ta, oi)': 'Taxable Income - (Salary, OI, CA, TA, OI)',
      'taxable income - (salary, oi, ca, ta, oi & pb)': 'Taxable Income - (Salary, OI, CA, TA, OI & PB)',
      'tax payable this month (salary, oi, ca, ta oi)': 'Tax Payable This Month (Salary, OI, CA, TA OI)',
      'tax payable this month (salary, oi, ca, ta, oi & pb)': 'Tax Payable This Month (Salary, OI, CA, TA, OI & PB)',
      'performance bonus tax': 'Performance Bonus Tax',
      'net (salary, oi, ca, ta, oi)': 'Net (Salary, OI, CA, TA, OI)',
      'net performance bonus': 'Net Performance Bonus',
      'penalty & deductions (after tax)': 'Penalty & Deductions (After Tax)',
      'total net (salary, oi, ca, ta, oi & pb)': 'Total Net (Salary, OI, CA, TA, OI & PB)',
      'employer pension contribution': 'Employer Pension Contribution',
      'eca': 'ECA',
      'management fees': 'Management Fees',
      'vat on management fees': 'VAT on Management Fees',
      'total cost': 'Total Cost',
      'wht on management fee': 'WHT on Management Fee',
      'sum payable': 'Sum Payable',
      'total cost($)': 'Total Cost(N)',
      'active or not': 'active or not',
      'pay opay': 'Pay OPay',
      'bank payment': 'Bank Payment',
      'submitter': 'Submitter',
      'opay account': 'OPay Account',
      'bvn': 'BVN',
      'bank name': 'Bank Name',
      'account name': 'Account Name',
      'account number': 'Account Number',
      'hr agency': 'HR Agency',
      'ba': 'BA',
      'pfa number': 'PFA Number',
      'email': 'Email'
    }
  }
};